/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vims;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.CharBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author indrajith
 */
public class ErrorNotification extends javax.swing.JFrame {

    /**
     * Creates new form ErrorNotification
     */
    public ErrorNotification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setOpaque(true);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setText("email id");

        jButton1.setText("validate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jTextField3.setText("jTextField3");

        jLayeredPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(190, 190, 190))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //dispalyEroorMessage(jTextField1.getText(), 50, 100 );
     // setErrorForTextField( jTextField1.getText(), jTextField1);
      //setErrorForTextField( jTextField2.getText(), jTextField2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
        void setErrorForTextField(String message, JTextField field, JFrame frame,JLayeredPane layer, int time,int Yvalue) {
        
        int globalX = frame.getX();
        int globalY = frame.getY();
        
        int x_0 = field.getX();
        int y_0 = field.getY();
        
        int x_l=layer.getX();
        int y_l=layer.getY();
       
        int width_0 = field.getWidth();
        int height_0 = field.getHeight();
        
        int targetX = 0;
        int targetY = 0;
        
       // height_0 = (int)height_0/2;
        targetX = x_0+width_0+3+globalX+x_l;
        targetY = y_0+height_0+globalY+5+y_l+Yvalue;
        
        
        System.err.println(targetX +"----"+targetY);
        System.err.println(globalX +"----"+globalY);
        System.err.println(x_l +"----"+y_l);
        dispalyEroorMessage( message, targetX, targetY, time );
        
    }
    
    void dispalyEroorMessage(String message, int x, int y, int time ) {
        javax.swing.JDialog error_show;
        JLabel  error_message, error_bg;
        error_show = new javax.swing.JDialog();
        error_message =  new JLabel();
        error_bg = new JLabel();
        error_show.setAlwaysOnTop(true);
        error_show.setUndecorated(true);
        error_show.setResizable(false);
        error_show.getContentPane().setLayout(new javax.swing.OverlayLayout(error_show.getContentPane()));

        error_message.setFont(new java.awt.Font("Arial", 1, 12));
        error_message.setForeground(new java.awt.Color(255, 255, 255));
       error_show.getContentPane().add(error_message);

        error_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error_bg_1.png")));
        error_show.getContentPane().add(error_bg);
        
        Border border = error_message.getBorder();
        Border margin = new EmptyBorder(0,15,0,0);
        error_message.setBorder(new CompoundBorder(border, margin));

        int string_length = message.length();
        System.err.println(""+string_length);
        int bou = 20+(string_length*9)+10;
        if ( bou > 600 )
            bou = 600;
        error_message.setText(message);
        error_show.setBackground(new java.awt.Color(0, 0, 0, 0));        
        error_show.setBounds(0, 0,bou , 45);
        
        //error_show.setLocation(x, y);   
        
        Thread ts = new Thread(
                new Runnable() {
            @Override
            public void run() {
                for( int i = 200; i>3; i--){
                    System.err.println("e"+i);
                     error_show.setLocation(x+i, y);   
                    try {
                        Thread.sleep((int)12-(i/20));
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }
        );
                
        Timer timer = new Timer(time, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
                error_show.setVisible(false);
                 ts.stop();
            }
        });
        timer.setRepeats(false);
        timer.start();
        error_show.setVisible(true);
        ts.start();
       
                
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErrorNotification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
   
}
