/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vims;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author subin stancil
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    String cUserId="";
    Boolean check=false;
    Boolean check2=false;
    public login() {
        initComponents();
        
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) 
            { setExtendedState(MAXIMIZED_BOTH);}
        });
        this.setLocationRelativeTo(null);
        layerRemoveAll(main1);
        layerAdd(main1,lgStaff);
        layerAdd(main1,bgrnd);
        
        checkExpire();
    }
        Staff s=new Staff();
        Admin a=new Admin();
    
            public void layerRemoveAll(JLayeredPane l1)
    {
               
        l1.removeAll();
        l1.repaint();
        l1.revalidate();
        
     
    }
    
    public void layerAdd(JLayeredPane l1,JLayeredPane l2)
    {
        
        
        l1.add(l2);
        l1.repaint();
        l1.revalidate();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        main = new javax.swing.JLayeredPane();
        main1 = new javax.swing.JLayeredPane();
        lgStaff = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        uname1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lgAdmin = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        uname2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bgrnd = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        sucess = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1360, 700));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1360, 700));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1360, 700));
        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        main1.setPreferredSize(new java.awt.Dimension(1360, 700));

        lgStaff.setLayout(new javax.swing.OverlayLayout(lgStaff));

        uname1.setBackground(new java.awt.Color(137, 123, 134));
        uname1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        uname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 123, 134), 2));
        uname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uname1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                uname1FocusLost(evt);
            }
        });
        uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(uname1);
        uname1.setBounds(120, 110, 250, 30);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(430, 100, 50, 110);

        pass1.setBackground(new java.awt.Color(137, 123, 134));
        pass1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 123, 134), 2));
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        jLayeredPane1.add(pass1);
        pass1.setBounds(120, 170, 250, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/staff.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(510, 30, 50, 20);

        lgStaff.add(jLayeredPane1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png"))); // NOI18N
        lgStaff.add(jLabel2);

        main1.add(lgStaff);
        lgStaff.setBounds(377, 181, 590, 300);

        lgAdmin.setLayout(new javax.swing.OverlayLayout(lgAdmin));

        uname2.setBackground(new java.awt.Color(137, 123, 134));
        uname2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        uname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 123, 134), 2));
        uname2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uname2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                uname2FocusLost(evt);
            }
        });
        uname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(uname2);
        uname2.setBounds(120, 110, 250, 30);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(430, 100, 50, 110);

        pass2.setBackground(new java.awt.Color(137, 123, 134));
        pass2.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 123, 134), 2));
        pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass2FocusLost(evt);
            }
        });
        jLayeredPane2.add(pass2);
        pass2.setBounds(120, 170, 250, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/admin.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(510, 30, 50, 20);

        lgAdmin.add(jLayeredPane2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png"))); // NOI18N
        lgAdmin.add(jLabel5);

        main1.add(lgAdmin);
        lgAdmin.setBounds(377, 181, 590, 300);

        bgrnd.setLayout(new javax.swing.OverlayLayout(bgrnd));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/bgrnlg.png"))); // NOI18N
        bgrnd.add(jLabel1);

        main1.add(bgrnd);
        bgrnd.setBounds(0, 0, 1360, 700);

        sucess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/lgSucess.png"))); // NOI18N
        sucess.setText("jLabel6");
        main1.add(sucess);
        sucess.setBounds(493, 312, 360, 47);

        fail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/fail.png"))); // NOI18N
        fail.setText("jLabel6");
        fail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                failMouseClicked(evt);
            }
        });
        main1.add(fail);
        fail.setBounds(489, 313, 360, 47);

        main.setLayer(main1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayout.createSequentialGroup()
                    .addComponent(main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainLayout.createSequentialGroup()
                    .addComponent(main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jDesktopPane1.add(main);

        jScrollPane1.setViewportView(jDesktopPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollBarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollBarUI());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname1ActionPerformed

    private void uname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uname1FocusGained
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginS.png")));
        uname1.setBackground(new java.awt.Color(255,255,255));
        uname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_uname1FocusGained

    private void uname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uname1FocusLost
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
        uname1.setBackground(new java.awt.Color(137,123,134));
        uname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
    }//GEN-LAST:event_uname1FocusLost

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginP.png")));
        pass1.setBackground(new java.awt.Color(255,255,255));
        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_pass1FocusGained

    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginS.png")));
        pass1.setBackground(new java.awt.Color(137,123,134));
        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
    }//GEN-LAST:event_pass1FocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
        String query="";
        try
        {
        Database db=new Database();
            db.jdbcConnect();
            query  ="Select * from login_staff where Employee_Id='"+uname1.getText()+"'";
             System.out.println(query);
            db.p=db.conn.prepareStatement(query);
            db.rs=db.p.executeQuery(query);
            while(db.rs.next())
            {
                if(db.rs.getString("Employee_Id").equals(uname1.getText())&&db.rs.getString("Password").equals(pass1.getText()))
                {
                    check=true;
                    s.cUserId=db.rs.getString("Employee_Id");
                    layerRemoveAll(main1);
                    main1.add(sucess);
                    main1.repaint();
                    main1.revalidate();
                    layerAdd(main1,lgStaff);
                    layerAdd(main1,bgrnd);
                }
                
            }
        }
        catch(Exception e)
        {
            
        }
        func();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void failMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_failMouseClicked
        // TODO add your handling code here:
//        layerRemoveAll(main1);
//        layerAdd(main1,lgStaff);
//        layerAdd(main1,bgrnd);
        main1.remove(fail);
        main1.repaint();
        main1.revalidate();
        
         jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
         jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
          uname1.setBackground(new java.awt.Color(137,123,134));
        uname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
         pass1.setBackground(new java.awt.Color(137,123,134));
        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
       // uname1.setText("");
        pass1.setText("");
        uname2.setBackground(new java.awt.Color(137,123,134));
        uname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
         pass2.setBackground(new java.awt.Color(137,123,134));
        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
       // uname2.setText("");
        pass2.setText("");
    }//GEN-LAST:event_failMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        layerRemoveAll(main1);
        layerAdd(main1,lgAdmin);
        layerAdd(main1,bgrnd);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
          uname2.setBackground(new java.awt.Color(137,123,134));
        uname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
         pass2.setBackground(new java.awt.Color(137,123,134));
        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
        uname2.setText("");
        pass2.setText("");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void uname2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uname2FocusGained
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginS.png")));
        uname2.setBackground(new java.awt.Color(255,255,255));
        uname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_uname2FocusGained

    private void uname2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uname2FocusLost
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
        uname2.setBackground(new java.awt.Color(137,123,134));
        uname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
    }//GEN-LAST:event_uname2FocusLost

    private void uname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_uname2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        
       String query="";
        try
        {
        Database db=new Database();
            db.jdbcConnect();
            query  ="Select * from login_admin where Employee_Id='"+uname2.getText()+"'";
             System.out.println(query);
            db.p=db.conn.prepareStatement(query);
            db.rs=db.p.executeQuery(query);
            while(db.rs.next())
            {
                if(db.rs.getString("Employee_Id").equals(uname2.getText())&&db.rs.getString("Password").equals(pass2.getText()))
                {
                    check2=true;
                    a.cUserId=db.rs.getString("Employee_Id");
                    layerRemoveAll(main1);
                    main1.add(sucess);
                    main1.repaint();
                    main1.revalidate();
                    layerAdd(main1,lgAdmin);
                    layerAdd(main1,bgrnd);
                }
                
            }
        }
        catch(Exception e)
        {
            
        }
        func2();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusGained
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginP.png")));
        pass2.setBackground(new java.awt.Color(255,255,255));
        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    }//GEN-LAST:event_pass2FocusGained

    private void pass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass2FocusLost
        // TODO add your handling code here:
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/loginS.png")));
        pass2.setBackground(new java.awt.Color(137,123,134));
        pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
    }//GEN-LAST:event_pass2FocusLost

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        layerRemoveAll(main1);
        layerAdd(main1,lgStaff);
        layerAdd(main1,bgrnd);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/lgn.png")));
          uname1.setBackground(new java.awt.Color(137,123,134));
        uname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
         pass1.setBackground(new java.awt.Color(137,123,134));
        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137,123,134), 2));
        uname1.setText("");
        pass1.setText("");
    }//GEN-LAST:event_jLabel7MouseClicked

    void func()
    {
        
            if(check==true)
            {
              
                s.show();
                this.dispose();
            }
            if(check==false)
            {
                layerRemoveAll(main1);
                main1.add(fail);
                main1.repaint();
                main1.revalidate();
                layerAdd(main1,lgStaff);
                layerAdd(main1,bgrnd);
            }
    }
   
    void func2()
    {
        if(check2==true)
            {
              
                a.show();
                this.dispose();
            }
            if(check2==false)
            {
                layerRemoveAll(main1);
                main1.add(fail);
                main1.repaint();
                main1.revalidate();
                layerAdd(main1,lgAdmin);
                layerAdd(main1,bgrnd);
            }
    }
    
    void checkExpire()
    {
        Calendar c=Calendar.getInstance();
        String query;
         try
        {
            Database db=new Database();
            db.jdbcConnect();
            query="select cust_id,end_date from policy";
             System.out.println(query);
            db.p=db.conn.prepareStatement(query);
            db.rs=db.p.executeQuery(query);
            while(db.rs.next())
            {
                System.err.println(db.rs.getDate("end_date"));
                if(db.rs.getDate("end_date").before(c.getTime()))
                {
                    query="update policy set status='Expired' where cust_id='"+db.rs.getString("cust_id")+"'";
                    System.err.println(query);
                    db.p=db.conn.prepareStatement(query);
                    int rs=db.p.executeUpdate(query);
                }
            }
            db.rs.close();
            db.p.close();
            db.conn.close();
        }
         catch(Exception e)
         {
             System.err.println(e);  
         }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
           // UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bgrnd;
    private javax.swing.JLabel fail;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane lgAdmin;
    private javax.swing.JLayeredPane lgStaff;
    private javax.swing.JLayeredPane main;
    private javax.swing.JLayeredPane main1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel sucess;
    private javax.swing.JTextField uname1;
    private javax.swing.JTextField uname2;
    // End of variables declaration//GEN-END:variables
}
